apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ht8m5z8rz-java-quarkus
  janus-idp.io/tekton: ht8m5z8rz-java-quarkus
  backstage.io/kubernetes-id: ht8m5z8rz-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ht8m5z8rz-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
